"""empty message

Revision ID: 1d959bede96f
Revises: 8548d72b8b9a
Create Date: 2018-05-21 10:28:55.612514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d959bede96f'
down_revision = '8548d72b8b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plate_dict',
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.Integer(), nullable=True),
    sa.Column('well', sa.String(), nullable=True),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('sample_type', sa.String(), nullable=True),
    sa.Column('experiment', sa.String(), nullable=True),
    sa.Column('sample_dilution', sa.String(), nullable=True),
    sa.Column('cell_donor', sa.String(), nullable=True),
    sa.Column('expt_id', sa.String(), nullable=True),
    sa.Column('expt_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('plate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plate_dict')
    # ### end Alembic commands ###
