"""empty message

Revision ID: 46f1b2e71e0d
Revises: 1d959bede96f
Create Date: 2018-05-21 10:50:29.262904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f1b2e71e0d'
down_revision = '1d959bede96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plate_dict', 'expt_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate_dict', sa.Column('expt_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
