"""empty message

Revision ID: 8db0787fc047
Revises: 
Create Date: 2018-05-17 10:28:46.865220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db0787fc047'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('expt_id', sa.String(), nullable=True),
    sa.Column('expt_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
